[package]
name = "sauce"
version = "0.0.1"
authors = ["Dan Cardin <ddcardin@gmail.com>"]
edition = "2018"
description = "A tool for managing directory-specific state."
documentation = "https://github.com/DanCardin/sauce"
homepage = "https://github.com/DanCardin/sauce"
repository = "https://github.com/DanCardin/sauce"
readme = "README.md"
keywords = ["source", "shell", "direnv"]
categories = ["command-line-utilities"]
license-file = "LICENSE"

[dependencies]
anyhow = "1.0.35"
arrayvec = "0.5.2"
clap = { version = "3.0.0-beta.2", features = ["suggestions", "color"] }
etcetera = "0.3.2"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5.7"
